POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Nova titul od root usera3.",
  "author": "John Smith4",
  "url": "https://root.com",
  "likes": 2,
  "userId": "66325c260a0b506c8eba8470"
}